### ISSUE TITLE
GMF, IMA ExoPlayer - Video ad not able to play, freezed at beginning

### ISSUE THREAD

**Issue by zvonkokemperle** [googleads/google-media-framework-android#51]
Hi,

Device: Sony Experia C5303
Android version: Android 4.3
Video: https://drive.google.com/file/d/0B4uXLfQfLJdAM0hUbzA3U1FIOTA/view

When using the latest GMF (Google Media Framework) which is using IMA Sdk with Exo Player the video ad freezes on the beginning and will not play until the application is resumed.
You can see this in the shared video. If I give it a push with the resume then the video starts to play.
I have also updated the included jar of the IMA from beta8 to the latest and built the exo_player lib with the latest surces and having the same issue.

Regards,

Zvonko

**Comment by tensafefrogs** [comment]
Are you using the last release, or are you using the version in the master branch?

**Comment by zvonkokemperle** [comment]
I am using version from master branch.

On Thu, Mar 26, 2015 at 6:33 PM, Geoff Stearns <notifications@github.com>
wrote:

> Are you using the last release, or are you using the version in the master
> branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googleads/google-media-framework-android/issues/51#issuecomment-86636311>
> .
>



-- 
Zvonimir Kemperle | Mobile: +386 51 321 935 <%2B38651321935> | Inova IT,
Pesnica 32e, 2211 Pesnica pri Maribor, Slovenia

**Comment by tensafefrogs** [comment]
Ok great, what is the android version and device you are using?

Did this work with a previous version of GMF, or is this your first time trying it out?

**Comment by tensafefrogs** [comment]
Ah sorry, I see you included that. I'll ask around and see if there's any known issues with the device or see if I can reproduce it.

**Comment by zvonkokemperle** [comment]
I was using this before, but not on this device.

Thanks,

Zvonko

On Thu, Mar 26, 2015 at 7:01 PM, Geoff Stearns <notifications@github.com>
wrote:

> Ah sorry, I see you included that. I'll ask around and see if there's any
> known issues with the device or see if I can reproduce it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googleads/google-media-framework-android/issues/51#issuecomment-86648186>
> .
>



-- 
Zvonimir Kemperle | Mobile: +386 51 321 935 <%2B38651321935> | Inova IT,
Pesnica 32e, 2211 Pesnica pri Maribor, Slovenia

**Comment by zvonkokemperle** [comment]
This one is solved here https://github.com/google/ExoPlayer/issues/376 in
the current Exo Player dev branch.

**Comment by anggras** [comment]
Sorry, which release of ExoPlayer that's working? Looks like 1.5.x is no longer compatible. Thanks in advance

**Comment by zvonkokemperle** [comment]
Hi,

in version 1.2.4

**Comment by anggras** [comment]
Thanks. But unfortunately seems like https://github.com/google/ExoPlayer/tree/r1.2.4 still have the problem.

I've forked this repo and made some modifications to support the latest Exoplayer 1.5.1 at https://github.com/Gratif/google-media-framework-android

Really appreciate if anyone can have a look and let me know if it's good. Will create a Pull Request if everything is okay.

**Comment by ypavlotsky** [comment]
Hi anggras,

I took a look at your changes, and they look good. We'd be interested in updating GMF to support the latest ExoPlayer; mind submitting a Pull Request? Thanks,

Yury
IMA SDK Team
